import Head from "next/head";
import Link from "next/link";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="page">
      <Head>
        <title>GameDev بالعربى</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
    </div>
  );
}
