import Head from "next/head";
import Link from "next/link";
import Hero from "../components/Hero";
import Projects from "../components/Projects";

const index = ({ projects }) => {
  return (
    <div className="page">
      <Head>
        <title>GameDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero />
      <Projects projects={projects} />
    </div>
  );
};

export default index;

export async function getStaticProps() {
  const res = await fetch(
    "https://my-json-server.typicode.com/Ibrahim-Rezq/portfolio_website/projects/"
  );
  const data = await res.json();
  return {
    props: {
      projects: [
        {
          userId: 1,
          id: 1,
          image: "/at.png",
          title:
            "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
          body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, sunt? Laborum ipsam alias vero in eos perspiciatis illum. Perferendis dignissimos omnis sapiente dolorem hic sint vel excepturi dicta necessitatibus! Neque eligendi dolores asperiores nemo non quidem fuga molestiae, consequatur tempore repudiandae eveniet quia hic in ipsa ut incidunt quo suscipit accusamus odio adipisci! Incidunt, repudiandae officia. Alias molestias veritatis vitae voluptatem beatae architecto, et ipsum odio dicta neque numquam eum labore veniam dolores magni velit praesentium nam nesciunt aut quibusdam quisquam iusto, rem sequi aperiam. Provident nostrum natus, cum nesciunt, doloribus ratione quod saepe ea cumque unde fugit voluptatum exercitationem!",
          catagory: ["sports", "sports", "sports"],
        },
        {
          userId: 1,
          id: 2,
          image: "/gz.png",
          title: "qui est esse",
          body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, sunt? Laborum ipsam alias vero in eos perspiciatis illum. Perferendis dignissimos omnis sapiente dolorem hic sint vel excepturi dicta necessitatibus! Neque eligendi dolores asperiores nemo non quidem fuga molestiae, consequatur tempore repudiandae eveniet quia hic in ipsa ut incidunt quo suscipit accusamus odio adipisci! Incidunt, repudiandae officia. Alias molestias veritatis vitae voluptatem beatae architecto, et ipsum odio dicta neque numquam eum labore veniam dolores magni velit praesentium nam nesciunt aut quibusdam quisquam iusto, rem sequi aperiam. Provident nostrum natus, cum nesciunt, doloribus ratione quod saepe ea cumque unde fugit voluptatum exercitationem!",
          catagory: ["sports"],
        },
        {
          userId: 1,
          id: 3,
          image: "/ir.png",
          title: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
          body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, sunt? Laborum ipsam alias vero in eos perspiciatis illum. Perferendis dignissimos omnis sapiente dolorem hic sint vel excepturi dicta necessitatibus! Neque eligendi dolores asperiores nemo non quidem fuga molestiae, consequatur tempore repudiandae eveniet quia hic in ipsa ut incidunt quo suscipit accusamus odio adipisci! Incidunt, repudiandae officia. Alias molestias veritatis vitae voluptatem beatae architecto, et ipsum odio dicta neque numquam eum labore veniam dolores magni velit praesentium nam nesciunt aut quibusdam quisquam iusto, rem sequi aperiam. Provident nostrum natus, cum nesciunt, doloribus ratione quod saepe ea cumque unde fugit voluptatum exercitationem!",
          catagory: ["politcs"],
        },
      ],
    },
  };
}
